// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvMPFVcwfzxdLPwVjp5E4lUO55oaB3e_I',
    appId: '1:46745721311:web:b913f72154e31369bb8c6a',
    messagingSenderId: '46745721311',
    projectId: 'flutter-app86',
    authDomain: 'flutter-app86.firebaseapp.com',
    storageBucket: 'flutter-app86.firebasestorage.app',
    measurementId: 'G-3Q9JCBLWX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKUpsqQ7WfM-0EIJ_wNJSyaUMhbgN6RPk',
    appId: '1:46745721311:android:b7bded9c4e819cdebb8c6a',
    messagingSenderId: '46745721311',
    projectId: 'flutter-app86',
    storageBucket: 'flutter-app86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3d0wxvQb3o1NLCk5ja6t-aAuifaD2tvg',
    appId: '1:46745721311:ios:abc62666a992a01abb8c6a',
    messagingSenderId: '46745721311',
    projectId: 'flutter-app86',
    storageBucket: 'flutter-app86.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3d0wxvQb3o1NLCk5ja6t-aAuifaD2tvg',
    appId: '1:46745721311:ios:abc62666a992a01abb8c6a',
    messagingSenderId: '46745721311',
    projectId: 'flutter-app86',
    storageBucket: 'flutter-app86.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvMPFVcwfzxdLPwVjp5E4lUO55oaB3e_I',
    appId: '1:46745721311:web:4cb43a44884d447abb8c6a',
    messagingSenderId: '46745721311',
    projectId: 'flutter-app86',
    authDomain: 'flutter-app86.firebaseapp.com',
    storageBucket: 'flutter-app86.firebasestorage.app',
    measurementId: 'G-CB55GXBM0E',
  );
}
